name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  publish_site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Jekyll
      run: gem install jekyll -v 4
    - name: Publish the microsite
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt -J-Xms4G -J-Xmx4G docs/publishMicrosite

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
    - name: Test
      run: sbt -J-Xms4G -J-Xmx4G +test
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
    - name: Compile documentation
      run: sbt -J-Xms4G -J-Xmx4G docs/mdoc
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
    - name: Check formatting
      run: sbt -J-Xms4G -J-Xmx4G scalafmtCheckAll scalafmtSbtCheck
